// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/fwojciec/packager"
	"sync"
)

// Ensure, that BuilderMock does implement packager.Builder.
// If this is not the case, regenerate this file with moq.
var _ packager.Builder = &BuilderMock{}

// BuilderMock is a mock implementation of packager.Builder.
//
// 	func TestSomethingThatUsesBuilder(t *testing.T) {
//
// 		// make and configure a mocked packager.Builder
// 		mockedBuilder := &BuilderMock{
// 			BuildFunc: func(tempProject packager.LocatorRemover) error {
// 				panic("mock out the Build method")
// 			},
// 		}
//
// 		// use mockedBuilder in code that requires packager.Builder
// 		// and then make assertions.
//
// 	}
type BuilderMock struct {
	// BuildFunc mocks the Build method.
	BuildFunc func(tempProject packager.LocatorRemover) error

	// calls tracks calls to the methods.
	calls struct {
		// Build holds details about calls to the Build method.
		Build []struct {
			// TempProject is the tempProject argument value.
			TempProject packager.LocatorRemover
		}
	}
	lockBuild sync.RWMutex
}

// Build calls BuildFunc.
func (mock *BuilderMock) Build(tempProject packager.LocatorRemover) error {
	if mock.BuildFunc == nil {
		panic("BuilderMock.BuildFunc: method is nil but Builder.Build was just called")
	}
	callInfo := struct {
		TempProject packager.LocatorRemover
	}{
		TempProject: tempProject,
	}
	mock.lockBuild.Lock()
	mock.calls.Build = append(mock.calls.Build, callInfo)
	mock.lockBuild.Unlock()
	return mock.BuildFunc(tempProject)
}

// BuildCalls gets all the calls that were made to Build.
// Check the length with:
//     len(mockedBuilder.BuildCalls())
func (mock *BuilderMock) BuildCalls() []struct {
	TempProject packager.LocatorRemover
} {
	var calls []struct {
		TempProject packager.LocatorRemover
	}
	mock.lockBuild.RLock()
	calls = mock.calls.Build
	mock.lockBuild.RUnlock()
	return calls
}
